sudo: reqiured
dist: trusty

cache:
  - pip

language: python
env:
  global:
    - LATEX_PACKAGES="texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-base texlive-bibtex-extra texlive-extra-utils texlive-font-utils texlive-binaries texlive-generic-extra texlive-generic-recommended texlive-lang-cyrillic texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-luatex texlive-math-extra texlive-pictures texlive-pstricks texlive-science texlive-xetex"
    - MAIN_FILE=examples/random_report.py

python:
  - "3.6"

before_install:
  - pip install -r requirements.txt
  - sudo apt-get -qq update && sudo apt-get install -y $LATEX_PACKAGES

script:
  - cd example && python $MAIN_FILE

before_deploy:
  - git config --local user.name "alekseik1"
  - git config --local user.email "alekseik1@yandex.ru"

deploy:
  provider: releases
  skip-cleanup: true
  api_key: $GITHUB_TOKEN
  file: "examples/test.pdf"
  overwrite: true
  on:
    tags: true